runtime: python39
entrypoint: gunicorn -b :$PORT Interactive viz:server

instance_class: F2

env_variables:
  PORT: 8080

automatic_scaling:
  target_cpu_utilization: 0.75
  min_instances: 1
  max_instances: 10

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

